version: '3.8'

services:
  np-fix:
    image: smoh92/np-fix:latest
    #If you use environment variables, 
    #delete the volumes section and enable the environment section. 
    volumes:
      - ./appsettings.json:/app/appsettings.json
    #environment:
    #  - API_HOST=localhost
    #  - API_PORT=8080
    #  - ENCRYPT_KEY=1234567890123456    